v0.1.3 Added Generator, dependencies, visualization updates, and name changes
NREL/REoptPlots.jl pull request #3
Opened 2023-02-02 23:04 UTC by bpulluta

2023-02-10 23:09 UTC, Bill-Becker requested changes
I confirmed my second comment that CSV has not been added, although you added loading CSV in by "using CSV". It's likely that you had CSV added to your local environment and that's why it worked locally for you. You'll need to add CSV to the REoptPlots.jl environment.

2023-02-10 23:09 UTC, Bill-Becker commented on Project.toml
> +DataFrames = "~1.4.4"
I've only seen the "minor" number be specified here, at most, so that would be "1.4". I also haven't seen the "~" before in [compat] - is that a thing?

2023-02-10 23:09 UTC, Bill-Becker commented on src/REoptPlots.jl
> +using CSV
I didn't see CSV in the Project.toml - is that added to this package's environment?

2023-02-13 17:08 UTC, bpulluta commented on Project.toml
> +DataFrames = "~1.4.4"
@Bill-Becker, thanks for catching that. Fixed in 718089545cea0d5c8cd11fda0cc8208465061a6b

2023-02-13 17:08 UTC, bpulluta commented on src/REoptPlots.jl
> +using CSV
@Bill-Becker, CSV is not necessary. Fixed in 408cd98d2f4673957beff8ef11a493c41cc60222

2023-02-13 20:59 UTC, Bill-Becker approved these changes
Looks good!

2023-02-14 21:59 UTC, merged